version: '3.8'

services:
  app:
    build: ./next-app
    command: npm run dev
    container_name: golearn-next
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - '3000:3000'
    depends_on:
      - database
    volumes:
      - ./next-app:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    networks:
      - node-network

  database:
    image: mongo:6-jammy
    container_name: golearn-mongodb
    ports:
      - '27017:27017'
    volumes:
      - golearndb:/data/db
    networks:
      - node-network

volumes:
  golearndb:

networks:
  node-network:
    driver: bridge
